[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bypassfuzzer"
version = "0.1.0"
dependencies = ["requests", "colorama"]
requires-python = ">=3.7"

[project.scripts]
bypassfuzzer = "bypassfuzzer:main"
